# Generated by Django 3.2.7 on 2021-09-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210918_2000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Organisation',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='user_profile',
            new_name='organisation',
        ),
    ]
